# 数据源
spring:
  application:
    name: redis_study
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis_study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 569332
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# MyBatis-Plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wkl.study.redis.redistudy.dataBase.po

server:
  port: 8081